# Ejercicio 1

<img src ='https://estaticos-cdn.prensaiberica.es/clip/23bf0054-14a8-40d0-8700-dc653638d702_16-9-discover-aspect-ratio_default_0.jpg' width=300>

Rafa, Nacho y Clara quieren comprar palmeras, donuts, hojaldres y tartas. Cada uno necesita diferentes cantidades y pueden elegir dos tiendas: *Manolo Bakes* y *Starbucks*. 

Las siguiente tablas muestran, respectivamente, la cantidad que cada uno necesita, y los precios en cada una de las tiendas

<table><thead><tr><th></th><th>Palmeras</th><th>Donuts</th><th>Hojaldres</th><th>Tartas</th></tr></thead><tbody><tr><td>Rafa</td><td>6</td><td>5</td><td>3</td><td>1</td></tr><tr><td>Nacho</td><td>3</td><td>6</td><td>2</td><td>2</td></tr><tr><td>Clara</td><td>3</td><td>4</td><td>3</td><td>1</td></tr></tbody></table>

<table><thead><tr><th></th><th>Manolo Bakes</th><th>Starbucks</th></tr></thead><tbody><tr><td>Palmera</td><td>1.50</td><td>1.00</td></tr><tr><td>Donut</td><td>2.00</td><td>2.50</td></tr><tr><td>Hojaldre</td><td>5.00</td><td>4.50</td></tr><tr><td>Tarta</td><td>16.00</td><td>17.00</td></tr></tbody></table>

Por ejemplo, si Rafa compra en *Manolo Bakes* gastaría:  

$6\cdot1.50+5\cdot2+3\cdot5+1\cdot16=50$  

y si compra en *Starbucks* gastaría:  

$6\cdot1+5\cdot2.50+3\cdot4.50+1\cdot17=49$  

**SE PIDE**: Genera la matriz que exprese la cantidad que cada persona gastaría en cada tienda, y recomienda a cada uno dónde debería hacer sus compras

In [1]:
import numpy as np

Compras = np.array([[6,5,3,1],
                    [3,6,2,2],
                    [3,4,3,1]])

Precios = np.array([[1.5,1.0],
                    [2.0,2.5],
                    [5.0,4.5],
                    [16.0,17.0]])

# Compras es una matriz de 3x4 y Precios una matriz de 4x2, así que pueden multiplicarse y dara como resultado una matriz de 3x2

# Matriz Inversion = Compras x Precios

Inversion = Compras.dot(Precios)

print(Inversion)

# Accedo a los valores de la matriz Inversion de 3x2 y los comparo para recomendar la mejor opción

if Inversion[0][0] < Inversion[0][1]:
    print('Rafa debería comprar en Manolo Bakes')
elif Inversion[0][0] > Inversion[0][1]:
    print('Rafa debería comprar en Starbucks')
else:
    print('Rafa puede comprar en cualquiera de los dos con el mismo gasto')
    
if Inversion[1][0] < Inversion[1][1]:
    print('Nacho debería comprar en Manolo Bakes')
elif Inversion[1][0] > Inversion[1][1]:
    print('Nacho debería comprar en Starbucks')
else:
    print('Nacho puede comprar en cualquiera de los dos con el mismo gasto')
    
if Inversion[2][0] < Inversion[2][1]:
    print('Clara debería comprar en Manolo Bakes')
elif Inversion[2][0] > Inversion[2][1]:
    print('Clara debería comprar en Starbucks')
else:
    print('Clara puede comprar en cualquiera de los dos con el mismo gasto')


[[50.  49. ]
 [58.5 61. ]
 [43.5 43.5]]
Rafa debería comprar en Starbucks
Nacho debería comprar en Manolo Bakes
Clara puede comprar en cualquiera de los dos con el mismo gasto


In [3]:
# Corrección:
recom = Inversion.argmin(axis=1) # "argmin" me dice si el minimo está en la primera o en la segunda posicion

tiendas = ['Manolo Bakes', 'Starbucks']
personas = ['Rafa', 'Nacho', 'Clara']

for index, persona in enumerate(personas):
    print(persona,'debe comprar en',tiendas[recom[index]])
    
# enumerate nos da el indice y el valor

Rafa debe comprar en Starbucks
Nacho debe comprar en Manolo Bakes
Clara debe comprar en Manolo Bakes


# Ejercicio 2
<img src='https://i0.wp.com/contraste.info/desarrollo/wp-content/uploads/2015/04/Marsattacks_FichaCine_5566706.jpg?fit=260%2C180&ssl=1' width="300">
                                                                                                
Hemos sido invadidos por los extraterrestres. El Gobierno ha prohibido toda comunicación escrita en castellano. Para poder comunicarnos, debemos generar mensajes de hasta 9 letras, codificados conforme al siguiente diccionario:

```Python
{'A':8,
 'B':7,
 'C':5,
 'D':13,
 'E':9,
 'F':16,
 'G':18,
 'H':22,
 'I':4,
 'J':23,
 'K':11,
 'L':3,
 'M':21,
 'N':1,
 'O':6,
 'P':15,
 'Q':12,
 'R':19,
 'S':2,
 'T':14,
 'U':17,
 'V':20,
 'W':25,
 'X':24,
 'Y':10,
 'Z':26
}
 
```

Por ejemplo, el mensaje "MARCIANOS" lo codificaríamos como "21 8 19 5 4 8 1 6 2"

Para poder enviar mensajes, debemos introducir los dígitos en una matriz 3x3. En este ejemplo, la matriz sería:

$$A=\begin{bmatrix}21 & 8 & 19 \\ 5 & 4 & 8 \\ 1 & 6 & 2\end{bmatrix}$$

A continuación, hay que multiplicar por la izquierda esta matriz por otra proporcionada por el Gobierno:

$$C=\begin{bmatrix}2 & 0 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 0\end{bmatrix}$$

Por tanto, el mensaje resultante sería:

$$Z = CA=\begin{bmatrix}2 & 0 & 1 \\ 1 & 0 & 1 \\ 0 & 1 & 0\end{bmatrix}\begin{bmatrix}21 & 8 & 19 \\ 5 & 4 & 8 \\ 1 & 6 & 2\end{bmatrix}=\begin{bmatrix}43 & 22 & 40 \\ 22 & 14 & 21 \\ 5 & 4 & 8\end{bmatrix}$$

El receptor del mensaje deberá decodificarlo multiplicando la matriz $Z$ por la matriz $C^{-1}$ (por la izquierda):

$$C^{-1}Z=A$$

**SE PIDE:**
1. Implementa una función para enviar mensajes de 9 letras codificados
> 1.1 Genera los dígitos correspondientes al mensaje a partir del diccionario y guárdalo en una lista  
> 1.2 Haz un reshape de la lista para transformarlo en un array de numpy 3x3  
> 1.3 Genera la matriz $Z=CA$, que será el output de la función
2. Implementa una función para decodificar mensajes de 9 letras
> 2.1 Crea un nuevo diccionario, donde se inviertan las claves y los valores del original  
> 2.2 Realiza la operación $C^{-1}Z=A$ y convierte la matriz a un vector con el método `flatten()`  
> 2.3 Recorre los elementos del vector para generar el mensaje decodificado usando el diccionario creado en 2.1

Consejo: Antes de implementar la función, reproduce el ejemplo del enunciado. Cuando te funcione, encapsula tu código en funciones

In [7]:
def codifica_mensajes_9_letras(palabra):
    palabra = palabra.upper()
    codigo = {'A':8,
             'B':7,
             'C':5,
             'D':13,
             'E':9,
             'F':16,
             'G':18,
             'H':22,
             'I':4,
             'J':23,
             'K':11,
             'L':3,
             'M':21,
             'N':1,
             'O':6,
             'P':15,
             'Q':12,
             'R':19,
             'S':2,
             'T':14,
             'U':17,
             'V':20,
             'W':25,
             'X':24,
             'Y':10,
             'Z':26
            }
    codificado = []
    for letra in palabra:
        codificado.append(codigo[letra])
    A = np.array(codificado).reshape(3,3)
    C = np.array([[2,0,1],
                  [1,0,1],
                  [0,1,0]])
    Z = C.dot(A)

    return Z

print(codifica_mensajes_9_letras("marcianos"))

[[43 22 40]
 [22 14 21]
 [ 5  4  8]]


In [44]:
# np.power(C,-1) Metodo Numpy para elevar una matriz a una potencia (No admite potencias negativas)

def decodifica_mensajes_9_letras(matriz):
    codigo = {'A':8,
             'B':7,
             'C':5,
             'D':13,
             'E':9,
             'F':16,
             'G':18,
             'H':22,
             'I':4,
             'J':23,
             'K':11,
             'L':3,
             'M':21,
             'N':1,
             'O':6,
             'P':15,
             'Q':12,
             'R':19,
             'S':2,
             'T':14,
             'U':17,
             'V':20,
             'W':25,
             'X':24,
             'Y':10,
             'Z':26
            }
    decodificador = {}
    for key,value in codigo.items():
        decodificador[value] = key
    C = np.array([[2,0,1],
                  [1,0,1],
                  [0,1,0]])
    C_inv = np.linalg.inv(C)
    A = (C_inv).dot(matriz)
    vector = A.flatten()
    palabra_codificada = []
    for i in vector:
        palabra_codificada.append(decodificador[i])
    palabra = ''.join(palabra_codificada)
    return palabra

In [45]:
M = codifica_mensajes_9_letras('imantados')
print(M)
print(decodifica_mensajes_9_letras(M))

[[21 48 18]
 [17 27 10]
 [ 1 14  8]]
IMANTADOS


In [ ]:
'''
Corrección Rafa:

def decodificador(Z,C):
    A2 = np.linalg.inv(C).dot(Z)
    
    mensaje = ''
    for dig in A2.flatten():
        mensaje += dic2[dig]
    return mensaje
    
Como la matriz del gobierno se actualiza, la función la coge como parametro de entrada
'''

# Ejercicio 3 

En el álgebra de matrices, existen tres tipos de matrices de especial interés:

1. **Matriz diagonal**: Todos los elementos son 0 excepto los de la diagonal
<img src='./img/diagonal.png' width = 200>

2. **Triangular superior**: Todos los elementos por encima de la diagonal son 0
<img src='./img/upper.png' width = 200>

3. **Triangular inferior**: Todos los elementos por debajo de la diagonal son 0
<img src='./img/lower.png' width = 200>

En numpy, las funciones `diag()`, `triu()` y `tril()` permiten hacer transformaciones de una matriz a cualquiera de las 3 anteriores

**CASO DE USO**


<img src='./img/bets.jpg' width=400>


En LaLiga se generan matrices como la siguiente, que indican la probabilidad estimada de cada resultado en un determinado partido:  

![SegmentLocal](./img/match_matrix.gif "segment")

Por ejemplo, la probabilidad estimada de que acaben 1-2 es del 3.37%  
La probabilidad de que acaben en empate sería la suma de la diagonal: $(0.0373+0.078+0.0409+0.0095+0.0012+0.0001)=16.7\%$

**SE PIDE**: 

1. Implementa una función que reciba una matriz cuadrada nxn y devuelva un diccionario con la probabilidad de empate, victoria local y victoria visitante. Asegúrate de que la suma de estas tres probabilidades es próxima a 1.

2. Implementa otra función que transforme el diccionario con las probabilidades a un diccionario de cuotas redondeado a 2 decimales (la cuota la calculamos como la inversa de la probabilidad)

Prueba con esta matriz
$$ P=\begin{bmatrix}0.0373 & 0.082 & 0.013 & 0.004\\ 0.1504 & 0.098 & 0.0337 & 0.0097 \\
0.121 & 0.194 & 0.04 & 0.0118 \\ 0.088 &  0.076 & 0.032 & 0.0091\end{bmatrix}$$

In [6]:
Probabilidades = np.array([[0.0373,0.082,0.013,0.004],
                           [0.1504,0.098,0.0337,0.0097],
                           [0.121,0.194,0.04,0.0118],
                           [0.088,0.076,0.032,0.0091]])

print(Probabilidades)

print(np.sum(Probabilidades)) # Me aseguro de que suma 1 para validar que los datos son correctos

print(np.diag(Probabilidades))

p_empate = sum(np.diag(Probabilidades))

print('La probabilidad de empate es del',str(p_empate*100)+'%')

print(np.triu(Probabilidades,1)) # También print(np.triu(Probabilidades,k=1))


p_visitante = np.sum(np.triu(Probabilidades,1)) # También print(np.triu(Probabilidades,k=1))

print('La probabilidad de victoria del equipo visitante es del',str(p_visitante*100)+'%')


print(np.tril(Probabilidades,-1)) # También print(np.tril(Probabilidades,k=-1))

p_local = np.sum(np.tril(Probabilidades,-1)) # También print(np.tril(Probabilidades,k=-1))

print('La probabilidad de victoria del equipo local es del',str(p_local*100)+'%')

[[0.0373 0.082  0.013  0.004 ]
 [0.1504 0.098  0.0337 0.0097]
 [0.121  0.194  0.04   0.0118]
 [0.088  0.076  0.032  0.0091]]
1.0
[0.0373 0.098  0.04   0.0091]
La probabilidad de empate es del 18.44%
[[0.     0.082  0.013  0.004 ]
 [0.     0.     0.0337 0.0097]
 [0.     0.     0.     0.0118]
 [0.     0.     0.     0.    ]]
La probabilidad de victoria del equipo visitante es del 15.42%
[[0.     0.     0.     0.    ]
 [0.1504 0.     0.     0.    ]
 [0.121  0.194  0.     0.    ]
 [0.088  0.076  0.032  0.    ]]
La probabilidad de victoria del equipo local es del 66.14%


In [18]:
def resultado_probable(matriz):
    p_empate = sum(np.diag(matriz))
    p_visitante = np.sum(np.triu(matriz,1))
    p_local = np.sum(np.tril(matriz,-1))
    dic_results = {'Victoria Local': (p_local),'Victoria Visitante': (p_visitante),'Empate': (p_empate)}
    return dic_results

# Mejor guardar en el diccionario el float que multiplicarlo por 100 para expresarlo como %

In [19]:
resultado_probable(Probabilidades)

{'Victoria Local': 0.6614, 'Victoria Visitante': 0.1542, 'Empate': 0.1844}

In [16]:
def cuotas_resultados(dic_results):
    dic_cuotas = dic_results.copy()
    for key,value in dic_results.items():
        dic_cuotas[key] = round(1/value,2)
    return dic_cuotas

In [17]:
cuotas_resultados(resultado_probable(Probabilidades))

{'Victoria Local': 0.02, 'Victoria Visitante': 0.06, 'Empate': 0.05}

In [ ]:
# Corrección Rafa:

def prob2cuota(d):
    cuota1 = round